# Generated by Django 4.2 on 2023-12-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='twiter_link',
            new_name='twitter_link',
        ),
    ]
